const bookmarks = [
    {
        id: 1,
        title: "Google",
        url:"https://www.google.com/",
        category: "search",
        subCategory: [],
        img:"",
    },
    {
        id: 2,
        title: "Startpage",
        url:"https://startpage.com/",
        category: "search",
        subCategory: [],
        img:"",
    },
    {
        id: 3,
        title: "DuckDuckGo",
        url:"https://duckduckgo.com/",
        category: "search",
        subCategory: [],
        img:"",
    },
    {
        id: 4,
        title: "THN",
        url:"https://thehackernews.com/",
        category: "News",
        subCategory: [],
        img:"",
    },
    {
        id: 5,
        title: "EttremeTech",
        url:"https://www.extremetech.com/",
        category: "News",
        subCategory: [],
        img:"",
    },
    {
        id: 6,
        title: "HaD",
        url:"https://hackaday.com/",
        category: "News",
        subCategory: [],
        img:"",
    },
    {
        id: 7,
        title: "Economist",
        url:"https://www.economist.com/",
        category: "News",
        subCategory: [],
        img:"",
    },
    {
        id: 8,
        title: "Hacker News",
        url:"https://news.ycombinator.com/",
        category: "News",
        subCategory: [],
        img:"",
    },
    {
        id: 9,
        title: "Triangle Calculator",
        url:"https://www.calculator.net/triangle-calculator.html",
        category: "Tools",
        subCategory: [math],
        img:"",
    },
    {
        id: 10,
        title: "Symbolab Math solver",
        url:"https://www.symbolab.com/",
        category: "Tools",
        subCategory: [math],
        img:"",
    },
    {
        id: 11,
        title: "WolframAlpha Math solver",
        url:"https://www.wolframalpha.com/",
        category: "Tools",
        subCategory: [math],
        img:"",
    },
    {
        id: 12,
        title: "DiffChecker",
        url:"https://www.diffchecker.com/",
        category: "Tools",
        subCategory: [text],
        img:"",
    },
    {
        id: 13,
        title: "CiteThisForMe citation maker",
        url:"https://www.citethisforme.com/",
        category: "Tools",
        subCategory: [text],
        img:"",
    },
    {
        id: 14,
        title: "MyBib citation maker",
        url:"https://www.mybib.com/",
        category: "Tools",
        subCategory: [text],
        img:"",
    },
]


export default bookmarks;