const bookmarksData = [
    {
        id: 1,
        title: "Google",
        url:"https://www.google.com/",
        category: "search",
        subCategory: [],
        img:"",
    },
    {
        id: 2,
        title: "Startpage",
        url:"https://startpage.com/",
        category: "search",
        subCategory: [],
        img:"",
    },
    {
        id: 3,
        title: "DuckDuckGo",
        url:"https://duckduckgo.com/",
        category: "search",
        subCategory: [],
        img:"",
    },
    {
        id: 4,
        title: "THN",
        url:"https://thehackernews.com/",
        category: "News",
        subCategory: [],
        img:"",
    },
    {
        id: 5,
        title: "EttremeTech",
        url:"https://www.extremetech.com/",
        category: "News",
        subCategory: [],
        img:"",
    },
    {
        id: 6,
        title: "HaD",
        url:"https://hackaday.com/",
        category: "News",
        subCategory: [],
        img:"",
    },
    {
        id: 7,
        title: "Economist",
        url:"https://www.economist.com/",
        category: "News",
        subCategory: [],
        img:"",
    },
    {
        id: 8,
        title: "Hacker News",
        url:"https://news.ycombinator.com/",
        category: "News",
        subCategory: [],
        img:"",
    },
    {
        id: 9,
        title: "Triangle Calculator",
        url:"https://www.calculator.net/triangle-calculator.html",
        category: "Tools",
        subCategory: ["math"],
        img:"",
    },
    {
        id: 10,
        title: "Symbolab Math solver",
        url:"https://www.symbolab.com/",
        category: "Tools",
        subCategory: ["math"],
        img:"",
    },
    {
        id: 11,
        title: "WolframAlpha Math solver",
        url:"https://www.wolframalpha.com/",
        category: "Tools",
        subCategory: ["math"],
        img:"",
    },
    {
        id: 12,
        title: "DiffChecker",
        url:"https://www.diffchecker.com/",
        category: "Tools",
        subCategory: ["text"],
        img:"",
    },
    {
        id: 13,
        title: "CiteThisForMe citation maker",
        url:"https://www.citethisforme.com/",
        category: "Tools",
        subCategory: ["text"],
        img:"",
    },
    {
        id: 14,
        title: "MyBib citation maker",
        url:"https://www.mybib.com/",
        category: "Tools",
        subCategory: ["text"],
        img:"",
    },
    {
        id: 15,
        title: "FreeCodeCamp",
        url:"https://www.freecodecamp.org/learn/",
        category: "dev",
        subCategory: [""],
        img:"",
    },
    {
        id: 17,
        title: "PythonTutor",
        url:"https://pythontutor.com/visualize.html#mode=edit",
        category: "dev",
        subCategory: [],
        img:"",
    },
    {
        id: 18,
        title: "leetCode",
        url:"https://leetcode.com/",
        category: "dev",
        subCategory: [],
        img:"",
    },
    {
        id: 19,
        title: "HackerRank",
        url:"https://www.hackerrank.com/",
        category: "dev",
        subCategory: [""],
        img:"",
    },
    {
        id: 20,
        title: "Python Dunder Methods",
        url:"https://levelup.gitconnected.com/python-dunder-methods-ea98ceabad15",
        category: "dev",
        subCategory: ["python"],
        img:"",
    },
    {
        id: 21,
        title: "Pynguin unit test generator",
        url:"https://github.com/se2p/pynguin",
        category: "dev",
        subCategory: ["python"],
        img:"",
    },
    {
        id: 22,
        title: "Nukita python compiler",
        url:"https://github.com/Nuitka/Nuitka",
        category: "dev",
        subCategory: ["python"],
        img:"",
    },
    {
        id: 23,
        title: "Dark Mode UI: the definitive guide",
        url:"https://uxdesign.cc/dark-mode-ui-design-the-definitive-guide-part-1-color-53dcfaea5129",
        category: "dev",
        subCategory: ["UI"],
        img:"",
    },
    {
        id: 24,
        title: "MyColor.space",
        url:"https://mycolor.space/",
        category: "dev",
        subCategory: ["UI"],
        img:"",
    },
    {
        id: 25,
        title: "Dark Mode UI: the definitive guide",
        url:"https://uxdesign.cc/dark-mode-ui-design-the-definitive-guide-part-1-color-53dcfaea5129",
        category: "dev",
        subCategory: ["UI"],
        img:"",
    },
    {
        id: 26,
        title: "Python Tkinter course",
        url:"https://www.youtube.com/watch?v=YXPyB4XeYLA",
        category: "dev",
        subCategory: ["UI","Tkinter"],
        img:"",
    },
    {
        id: 27,
        title: "TkDocs python",
        url:"https://tkdocs.com/shipman/index-2.html",
        category: "dev",
        subCategory: ["UI","Tkinter"],
        img:"",
    },
]


export default bookmarksData;